image: ubuntu:latest

stages:
  - lint

shellcheck:
  stage: lint
  before_script:
    - apt update && apt install -y shellcheck
    - shellcheck --version
  script:
    - shellcheck init_backup.sh manage_backup.sh